CREATE TABLE articles(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title varchar(600) NOT NULL,
	content MEDIUMTEXT NOT NULL,
	editor VARCHAR(255) NOT NULL DEFAULT 'Shane Wiker',
	description VARCHAR(500) NOT NULL,
	coverUrl TEXT NOT NULL,
	category VARCHAR(300) NOT NULL,
	visitorsNo INT DEFAULT 0,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE admins(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100),
	password varchar(100),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE newsletter (
     id INT PRIMARY KEY AUTO_INCREMENT,
     email VARCHAR(255) NOT NULL,
     createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);